# Generated by Django 5.2.15 on 2026-06-21 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.CharField(max_length=255)),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("user_role", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=500)),
                ("allowed", models.BooleanField(default=True)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "entra_token_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="identity_au_timesta_935647_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="identity_au_user_id_d4585a_idx"
                    ),
                    models.Index(
                        fields=["entra_token_id"], name="identity_au_entra_t_e8b944_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityMap",
            fields=[
                (
                    "entra_oid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("emplid", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="identity_id_email_157d2d_idx")
                ],
            },
        ),
    ]
