# Generated by Django 5.2.15 on 2026-06-21 21:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("cron", models.CharField(blank=True, default="", max_length=100)),
                ("source", models.CharField(max_length=255)),
                ("tool", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("full", "Full refresh"),
                            ("delta", "Delta refresh"),
                            ("event", "Event-driven"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                (
                    "text_memories_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "structured_cache_table",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schedule_name", models.CharField(max_length=255)),
                ("source_system", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["schedule_name"], name="sync_syncru_schedul_a07077_idx"
                    ),
                    models.Index(
                        fields=["status"], name="sync_syncru_status_d90ad7_idx"
                    ),
                ],
            },
        ),
    ]
