"""PostgreSQL cache schema generation (Component 6.1).

Generates ``CREATE TABLE`` statements for the local cache from a discovery
:class:`SchemaManifest`. The cache is a denormalized projection of the source
schema optimized for the queries MCP tools will run. Django-free.
"""

from __future__ import annotations

import logging
from typing import Optional

from iblai_ontology.backend.discovery.introspection import SchemaManifest, TableInfo

logger = logging.getLogger("iblai_ontology.provisioning")

# Source DB type -> PostgreSQL type.
TYPE_MAPPING = {
    # Oracle
    "VARCHAR2": "TEXT",
    "NVARCHAR2": "TEXT",
    "CHAR": "TEXT",
    "NCHAR": "TEXT",
    "CLOB": "TEXT",
    "NCLOB": "TEXT",
    "NUMBER": "NUMERIC",
    "FLOAT": "DOUBLE PRECISION",
    "DATE": "TIMESTAMP",
    "TIMESTAMP(6)": "TIMESTAMP",
    "TIMESTAMP(6) WITH TIME ZONE": "TIMESTAMPTZ",
    "RAW": "BYTEA",
    "BLOB": "BYTEA",
    "LONG": "TEXT",
    # MySQL
    "int": "INTEGER",
    "bigint": "BIGINT",
    "tinyint": "SMALLINT",
    "varchar": "TEXT",
    "text": "TEXT",
    "datetime": "TIMESTAMP",
    "decimal": "NUMERIC",
    # SQL Server
    "nvarchar": "TEXT",
    "uniqueidentifier": "UUID",
    "bit": "BOOLEAN",
    "money": "NUMERIC(19,4)",
    "smallmoney": "NUMERIC(10,4)",
}


class CacheSchemaGenerator:
    """Generates PostgreSQL CREATE TABLE statements for the local cache."""

    def __init__(self, manifest: SchemaManifest, entity_groups: Optional[dict] = None) -> None:
        self.manifest = manifest
        self.entity_groups = entity_groups or {}

    def _select_tables(self, tables_to_cache: Optional[list[str]]) -> list[TableInfo]:
        if tables_to_cache:
            return [t for t in self.manifest.tables if t.table_name in tables_to_cache]
        if self.entity_groups:
            grouped: set[str] = set()
            for group_tables in self.entity_groups.values():
                grouped.update(group_tables)
            return [t for t in self.manifest.tables if t.table_name in grouped]
        return [t for t in self.manifest.tables if t.row_count < 1_000_000]

    def generate(self, tables_to_cache: Optional[list[str]] = None) -> str:
        tables = self._select_tables(tables_to_cache)
        lines = [
            "-- ==============================================================",
            "-- iblai-ontology Cache Schema",
            f"-- Source: {self.manifest.database} ({self.manifest.db_type})",
            "-- Generated by the provisioning engine",
            f"-- Tables: {len(tables)}",
            "-- ==============================================================",
            "",
            "CREATE SCHEMA IF NOT EXISTS cache;",
            "",
        ]
        for table in tables:
            lines.extend(self._generate_table(table))
            lines.append("")
        lines.append("-- Indexes")
        for table in tables:
            lines.extend(self._generate_indexes(table))
        return "\n".join(lines)

    def _generate_table(self, table: TableInfo) -> list[str]:
        cache_name = self._to_cache_name(table.table_name)
        lines = [
            f"-- Source: {table.schema_name}.{table.table_name} ({table.row_count:,} rows)",
            f"CREATE TABLE IF NOT EXISTS cache.{cache_name} (",
        ]
        col_defs = []
        for col in table.columns:
            pg_type = self._map_type(col.data_type)
            nullable = "" if col.nullable else " NOT NULL"
            col_defs.append(f"    {col.name.lower()} {pg_type}{nullable}")
        col_defs.append("    _synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()")
        col_defs.append("    _source_schema TEXT NOT NULL DEFAULT ''")
        col_defs.append("    _source_table TEXT NOT NULL DEFAULT ''")
        if table.primary_key_columns:
            pk_cols = ", ".join(c.lower() for c in table.primary_key_columns)
            col_defs.append(f"    PRIMARY KEY ({pk_cols})")
        lines.append(",\n".join(col_defs))
        lines.append(");")
        return lines

    def _generate_indexes(self, table: TableInfo) -> list[str]:
        cache_name = self._to_cache_name(table.table_name)
        indexes = [
            f"CREATE INDEX IF NOT EXISTS idx_{cache_name}_synced_at "
            f"ON cache.{cache_name} (_synced_at);"
        ]
        for fk in table.foreign_keys:
            col = fk["column"].lower()
            indexes.append(
                f"CREATE INDEX IF NOT EXISTS idx_{cache_name}_{col} "
                f"ON cache.{cache_name} ({col});"
            )
        return indexes

    def _map_type(self, source_type: str) -> str:
        if source_type.upper() in TYPE_MAPPING:
            return TYPE_MAPPING[source_type.upper()]
        if source_type.lower() in TYPE_MAPPING:
            return TYPE_MAPPING[source_type.lower()]
        for pattern, pg_type in TYPE_MAPPING.items():
            if source_type.upper().startswith(pattern.upper()):
                return pg_type
        return "TEXT"

    @staticmethod
    def _to_cache_name(table_name: str) -> str:
        name = table_name.lower()
        for prefix in ("ps_", "spriden_", "sgbstdn_"):
            if name.startswith(prefix):
                return name[len(prefix):]
        return name

    def write_to_file(self, output_path: str, tables_to_cache: Optional[list[str]] = None) -> None:
        with open(output_path, "w") as f:
            f.write(self.generate(tables_to_cache))
