# Generated by Django 5.2.15 on 2026-06-21 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("database", "Database"), ("api", "REST API")],
                        max_length=20,
                    ),
                ),
                ("adapter", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Setup"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                (
                    "connection_config_encrypted",
                    models.BinaryField(blank=True, null=True),
                ),
                ("schema_manifest", models.JSONField(blank=True, null=True)),
                ("llm_analysis", models.JSONField(blank=True, null=True)),
                ("last_discovery_at", models.DateTimeField(blank=True, null=True)),
                ("last_safety_check_at", models.DateTimeField(blank=True, null=True)),
                ("safety_status", models.CharField(default="pending", max_length=20)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(default="never_run", max_length=20)),
                ("tables_synced", models.IntegerField(default=0)),
                ("rows_synced", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("connected", models.BooleanField(default=False)),
                ("read_only", models.BooleanField(default=False)),
                ("latency_ms", models.IntegerField(default=0)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.JSONField(default=dict)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
