import type { CatalogEntry, Domain } from "./types";

export const DOMAINS: Domain[] = [
  "enterprise",
  "financial-services",
  "government",
  "higher-ed",
  "k-12",
  "legal",
  "medical-healthcare",
];

export const CATALOG: CatalogEntry[] = [
  {
    key: "peoplesoft",
    display_name: "PeopleSoft (Oracle)",
    type: "database",
    domain: "higher-ed",
    adapter: "peoplesoft",
    default_toolset: "enrollment-tools",
    skill: null,
    summary:
      "Campus Solutions SIS on Oracle — students, enrollment, financial aid, courses, HR (PS_* tables, EMPLID keys).",
    env: [
      "PEOPLESOFT_DB_HOST",
      "PEOPLESOFT_DB_PORT",
      "PEOPLESOFT_DB_NAME",
      "PEOPLESOFT_RO_USER",
      "PEOPLESOFT_RO_PASSWORD",
    ],
    connection: { driver: "oracle", default_port: 1521 },
    sync_defaults: { students: "1h", courses: "6h", financial_aid: "1h", demographics: "24h" },
  },
  {
    key: "banner",
    display_name: "Ellucian Banner (REST)",
    type: "api",
    domain: "higher-ed",
    adapter: "banner_api",
    default_toolset: "enrollment-tools",
    skill: "banner.md",
    summary: "",
    env: ["BANNER_API_KEY", "BANNER_BASE_URL", "BANNER_CLIENT_ID", "BANNER_CLIENT_SECRET"],
    connection: { base_url_env: "BANNER_BASE_URL" },
    sync_defaults: { students: "1h", registration: "1h", financial_aid: "6h" },
  },
  {
    key: "canvas",
    display_name: "Instructure Canvas LMS",
    type: "api",
    domain: "higher-ed",
    adapter: "canvas_api",
    default_toolset: "enrollment-tools",
    skill: "canvas.md",
    summary: "",
    env: ["CANVAS_API_TOKEN", "CANVAS_BASE_URL"],
    connection: { base_url_env: "CANVAS_BASE_URL" },
    sync_defaults: { activity: "4h", submissions: "1h" },
  },
  {
    key: "slate",
    display_name: "Technolutions Slate CRM",
    type: "api",
    domain: "higher-ed",
    adapter: "slate_api",
    default_toolset: "admin-analytics-tools",
    skill: "slate.md",
    summary: "",
    env: ["SLATE_API_KEY", "SLATE_BASE_URL"],
    connection: { base_url_env: "SLATE_BASE_URL" },
    sync_defaults: { applications: "6h" },
  },
  {
    key: "workday",
    display_name: "Workday HCM / Student",
    type: "api",
    domain: "higher-ed",
    adapter: "workday_api",
    default_toolset: "admin-analytics-tools",
    skill: "workday.md",
    summary: "",
    env: ["WORKDAY_CLIENT_ID", "WORKDAY_CLIENT_SECRET", "WORKDAY_BASE_URL", "WORKDAY_TENANT"],
    connection: { base_url_env: "WORKDAY_BASE_URL" },
    sync_defaults: { workers: "24h", financial_aid: "6h" },
  },
  {
    key: "eab-navigate",
    display_name: "EAB Navigate",
    type: "api",
    domain: "higher-ed",
    adapter: "navigate_api",
    default_toolset: "enrollment-tools",
    skill: "eab-navigate.md",
    summary: "",
    env: ["EAB_NAVIGATE_API_KEY", "EAB_NAVIGATE_BASE_URL"],
    connection: { base_url_env: "EAB_NAVIGATE_BASE_URL" },
    sync_defaults: { alerts: "1h", appointments: "6h" },
  },
  {
    key: "salesforce-education-cloud",
    display_name: "Salesforce Education Cloud",
    type: "api",
    domain: "higher-ed",
    adapter: "salesforce_api",
    default_toolset: "admin-analytics-tools",
    skill: "salesforce-education-cloud.md",
    summary: "",
    env: [
      "SALESFORCE_CLIENT_ID",
      "SALESFORCE_CLIENT_SECRET",
      "SALESFORCE_INSTANCE_URL",
      "SALESFORCE_USERNAME",
      "SALESFORCE_PASSWORD",
    ],
    connection: { base_url_env: "SALESFORCE_INSTANCE_URL" },
    sync_defaults: { contacts: "6h", opportunities: "6h" },
  },
  {
    key: "servicenow",
    display_name: "ServiceNow ITSM",
    type: "api",
    domain: "higher-ed",
    adapter: "servicenow_api",
    default_toolset: "admin-analytics-tools",
    skill: "servicenow.md",
    summary: "",
    env: ["SERVICENOW_CLIENT_ID", "SERVICENOW_CLIENT_SECRET", "SERVICENOW_BASE_URL"],
    connection: { base_url_env: "SERVICENOW_BASE_URL" },
    sync_defaults: { incidents: "1h" },
  },
  {
    key: "civitas-learning",
    display_name: "Civitas Learning",
    type: "api",
    domain: "higher-ed",
    adapter: "civitas_api",
    default_toolset: "enrollment-tools",
    skill: "civitas-learning.md",
    summary: "",
    env: ["CIVITAS_API_KEY", "CIVITAS_BASE_URL"],
    connection: { base_url_env: "CIVITAS_BASE_URL" },
    sync_defaults: { risk_scores: "6h" },
  },
  {
    key: "handshake",
    display_name: "Handshake Careers",
    type: "api",
    domain: "higher-ed",
    adapter: "handshake_api",
    default_toolset: "admin-analytics-tools",
    skill: "handshake.md",
    summary: "",
    env: ["HANDSHAKE_API_KEY", "HANDSHAKE_BASE_URL"],
    connection: { base_url_env: "HANDSHAKE_BASE_URL" },
    sync_defaults: { jobs: "24h" },
  },
  {
    key: "blackbaud-raisers-edge",
    display_name: "Blackbaud Raiser's Edge NXT",
    type: "api",
    domain: "higher-ed",
    adapter: "raisers_edge_api",
    default_toolset: "admin-analytics-tools",
    skill: "blackbaud-raisers-edge.md",
    summary: "",
    env: [
      "RAISERS_EDGE_API_KEY",
      "RAISERS_EDGE_CLIENT_ID",
      "RAISERS_EDGE_CLIENT_SECRET",
      "RAISERS_EDGE_BASE_URL",
      "RAISERS_EDGE_REDIRECT_URI",
    ],
    connection: { base_url_env: "RAISERS_EDGE_BASE_URL" },
    sync_defaults: { constituents: "24h", gifts: "6h" },
  },
  {
    key: "snowflake",
    display_name: "Snowflake Data Warehouse",
    type: "database",
    domain: "enterprise",
    adapter: "snowflake",
    default_toolset: "admin-analytics-tools",
    skill: "snowflake.md",
    summary: "",
    env: [
      "SNOWFLAKE_ACCOUNT",
      "SNOWFLAKE_USER",
      "SNOWFLAKE_PASSWORD",
      "SNOWFLAKE_WAREHOUSE",
      "SNOWFLAKE_DATABASE",
      "SNOWFLAKE_SCHEMA",
      "SNOWFLAKE_ROLE",
    ],
    connection: { driver: "snowflake" },
    sync_defaults: { tables: "6h" },
  },
  {
    key: "salesforce",
    display_name: "Salesforce CRM / Sales Cloud",
    type: "api",
    domain: "enterprise",
    adapter: "salesforce_api",
    default_toolset: "admin-analytics-tools",
    skill: "salesforce.md",
    summary: "",
    env: [
      "SALESFORCE_CLIENT_ID",
      "SALESFORCE_CLIENT_SECRET",
      "SALESFORCE_INSTANCE_URL",
      "SALESFORCE_USERNAME",
      "SALESFORCE_PASSWORD",
      "SALESFORCE_SECURITY_TOKEN",
    ],
    connection: { base_url_env: "SALESFORCE_INSTANCE_URL" },
    sync_defaults: { opportunities: "6h", accounts: "6h" },
  },
  {
    key: "hubspot",
    display_name: "HubSpot CRM",
    type: "api",
    domain: "enterprise",
    adapter: "hubspot_api",
    default_toolset: "admin-analytics-tools",
    skill: "hubspot.md",
    summary: "",
    env: ["HUBSPOT_ACCESS_TOKEN"],
    connection: { base_url: "https://api.hubapi.com" },
    sync_defaults: { deals: "6h", contacts: "6h" },
  },
  {
    key: "servicenow-itsm",
    display_name: "ServiceNow ITSM (enterprise)",
    type: "api",
    domain: "enterprise",
    adapter: "servicenow_api",
    default_toolset: "admin-analytics-tools",
    skill: "servicenow.md",
    summary: "",
    env: ["SERVICENOW_CLIENT_ID", "SERVICENOW_CLIENT_SECRET", "SERVICENOW_BASE_URL"],
    connection: { base_url_env: "SERVICENOW_BASE_URL" },
    sync_defaults: { incidents: "1h" },
  },
  {
    key: "jira",
    display_name: "Jira",
    type: "api",
    domain: "enterprise",
    adapter: "jira_api",
    default_toolset: "admin-analytics-tools",
    skill: "jira.md",
    summary: "",
    env: ["JIRA_BASE_URL", "JIRA_USER_EMAIL", "JIRA_API_TOKEN"],
    connection: { base_url_env: "JIRA_BASE_URL" },
    sync_defaults: { issues: "1h" },
  },
  {
    key: "confluence",
    display_name: "Confluence",
    type: "api",
    domain: "enterprise",
    adapter: "confluence_api",
    default_toolset: "admin-analytics-tools",
    skill: "confluence.md",
    summary: "",
    env: ["CONFLUENCE_BASE_URL", "CONFLUENCE_USER_EMAIL", "CONFLUENCE_API_TOKEN"],
    connection: { base_url_env: "CONFLUENCE_BASE_URL" },
    sync_defaults: { pages: "24h" },
  },
  {
    key: "github",
    display_name: "GitHub",
    type: "api",
    domain: "enterprise",
    adapter: "github_api",
    default_toolset: "admin-analytics-tools",
    skill: "github.md",
    summary: "",
    env: ["GITHUB_TOKEN"],
    connection: { base_url: "https://api.github.com" },
    sync_defaults: { repos: "24h" },
  },
  {
    key: "okta",
    display_name: "Okta Identity",
    type: "api",
    domain: "enterprise",
    adapter: "okta_api",
    default_toolset: "admin-analytics-tools",
    skill: "okta.md",
    summary: "",
    env: ["OKTA_DOMAIN", "OKTA_API_TOKEN"],
    connection: { base_url_env: "OKTA_DOMAIN" },
    sync_defaults: { users: "24h" },
  },
  {
    key: "slack",
    display_name: "Slack",
    type: "api",
    domain: "enterprise",
    adapter: "slack_api",
    default_toolset: "admin-analytics-tools",
    skill: "slack.md",
    summary: "",
    env: ["SLACK_BOT_TOKEN", "SLACK_SIGNING_SECRET"],
    connection: { base_url: "https://slack.com/api" },
    sync_defaults: { channels: "24h" },
  },
  {
    key: "zendesk",
    display_name: "Zendesk",
    type: "api",
    domain: "enterprise",
    adapter: "zendesk_api",
    default_toolset: "admin-analytics-tools",
    skill: "zendesk.md",
    summary: "",
    env: ["ZENDESK_SUBDOMAIN", "ZENDESK_EMAIL", "ZENDESK_API_TOKEN"],
    connection: { base_url_env: "ZENDESK_SUBDOMAIN" },
    sync_defaults: { tickets: "1h" },
  },
  {
    key: "zoom",
    display_name: "Zoom",
    type: "api",
    domain: "enterprise",
    adapter: "zoom_api",
    default_toolset: "admin-analytics-tools",
    skill: "zoom.md",
    summary: "",
    env: ["ZOOM_ACCOUNT_ID", "ZOOM_CLIENT_ID", "ZOOM_CLIENT_SECRET"],
    connection: { base_url: "https://api.zoom.us/v2" },
    sync_defaults: { meetings: "24h" },
  },
  {
    key: "oracle-epm-cloud",
    display_name: "Oracle EPM Cloud",
    type: "api",
    domain: "enterprise",
    adapter: "oracle_epm_api",
    default_toolset: "admin-analytics-tools",
    skill: "oracle-epm-cloud.md",
    summary: "",
    env: [
      "ORACLE_EPM_BASE_URL",
      "ORACLE_EPM_IDENTITY_DOMAIN",
      "ORACLE_EPM_USERNAME",
      "ORACLE_EPM_PASSWORD",
    ],
    connection: { base_url_env: "ORACLE_EPM_BASE_URL" },
    sync_defaults: { applications: "24h", jobs: "6h" },
  },
  {
    key: "classdojo",
    display_name: "ClassDojo",
    type: "api",
    domain: "k-12",
    adapter: "classdojo_api",
    default_toolset: "enrollment-tools",
    skill: "classdojo.md",
    summary: "",
    env: ["CLASSDOJO_API_KEY", "CLASSDOJO_TEACHER_ID"],
    connection: {},
    sync_defaults: { activity: "6h" },
  },
  {
    key: "ebsco",
    display_name: "EBSCO Discovery",
    type: "api",
    domain: "k-12",
    adapter: "ebsco_api",
    default_toolset: "admin-analytics-tools",
    skill: "ebsco.md",
    summary: "",
    env: ["EBSCO_API_KEY", "EBSCO_PROFILE_ID", "EBSCO_BASE_URL"],
    connection: { base_url_env: "EBSCO_BASE_URL" },
    sync_defaults: { catalog: "24h" },
  },
  {
    key: "edulastic",
    display_name: "Edulastic Assessments",
    type: "api",
    domain: "k-12",
    adapter: "edulastic_api",
    default_toolset: "enrollment-tools",
    skill: "edulastic.md",
    summary: "",
    env: ["EDULASTIC_API_KEY", "EDULASTIC_DISTRICT_ID"],
    connection: {},
    sync_defaults: { assessments: "24h" },
  },
  {
    key: "frontline",
    display_name: "Frontline Education",
    type: "api",
    domain: "k-12",
    adapter: "frontline_api",
    default_toolset: "admin-analytics-tools",
    skill: "frontline.md",
    summary: "",
    env: ["FRONTLINE_CLIENT_ID", "FRONTLINE_CLIENT_SECRET", "FRONTLINE_BASE_URL"],
    connection: { base_url_env: "FRONTLINE_BASE_URL" },
    sync_defaults: { absences: "6h" },
  },
  {
    key: "google-classroom",
    display_name: "Google Classroom",
    type: "api",
    domain: "k-12",
    adapter: "google_classroom_api",
    default_toolset: "enrollment-tools",
    skill: "google-classroom.md",
    summary: "",
    env: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    connection: { base_url: "https://classroom.googleapis.com" },
    sync_defaults: { coursework: "6h" },
  },
  {
    key: "google-workspace-edu",
    display_name: "Google Workspace for Education",
    type: "api",
    domain: "k-12",
    adapter: "google_workspace_edu_api",
    default_toolset: "admin-analytics-tools",
    skill: "google-workspace-edu.md",
    summary: "",
    env: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    connection: { base_url: "https://admin.googleapis.com" },
    sync_defaults: { users: "24h" },
  },
  {
    key: "iready",
    display_name: "i-Ready",
    type: "api",
    domain: "k-12",
    adapter: "iready_api",
    default_toolset: "enrollment-tools",
    skill: "iready.md",
    summary: "",
    env: ["IREADY_API_KEY", "IREADY_DISTRICT_ID"],
    connection: {},
    sync_defaults: { assessments: "24h" },
  },
  {
    key: "khan-academy",
    display_name: "Khan Academy",
    type: "api",
    domain: "k-12",
    adapter: "khan_academy_api",
    default_toolset: "enrollment-tools",
    skill: "khan-academy.md",
    summary: "",
    env: ["KHAN_ACADEMY_CLIENT_ID", "KHAN_ACADEMY_CLIENT_SECRET", "KHAN_ACADEMY_REDIRECT_URI"],
    connection: {},
    sync_defaults: { progress: "24h" },
  },
  {
    key: "nwea-map",
    display_name: "NWEA MAP Growth",
    type: "api",
    domain: "k-12",
    adapter: "nwea_map_api",
    default_toolset: "enrollment-tools",
    skill: "nwea-map.md",
    summary: "",
    env: ["NWEA_MAP_API_KEY", "NWEA_MAP_BASE_URL"],
    connection: { base_url_env: "NWEA_MAP_BASE_URL" },
    sync_defaults: { assessments: "24h" },
  },
  {
    key: "parentsquare",
    display_name: "ParentSquare",
    type: "api",
    domain: "k-12",
    adapter: "parentsquare_api",
    default_toolset: "admin-analytics-tools",
    skill: "parentsquare.md",
    summary: "",
    env: ["PARENTSQUARE_API_KEY", "PARENTSQUARE_DISTRICT_ID"],
    connection: {},
    sync_defaults: { messages: "6h" },
  },
  {
    key: "powerschool",
    display_name: "PowerSchool SIS",
    type: "api",
    domain: "k-12",
    adapter: "powerschool_api",
    default_toolset: "enrollment-tools",
    skill: "powerschool.md",
    summary: "",
    env: ["POWERSCHOOL_CLIENT_ID", "POWERSCHOOL_CLIENT_SECRET", "POWERSCHOOL_BASE_URL"],
    connection: { base_url_env: "POWERSCHOOL_BASE_URL" },
    sync_defaults: { students: "1h", enrollment: "1h" },
  },
  {
    key: "congress-gov",
    display_name: "Congress.gov",
    type: "api",
    domain: "government",
    adapter: "congress_gov_api",
    default_toolset: "admin-analytics-tools",
    skill: "congress-gov.md",
    summary: "",
    env: ["CONGRESS_GOV_API_KEY"],
    connection: { base_url: "https://api.congress.gov/v3" },
    sync_defaults: { bills: "24h" },
  },
  {
    key: "cornerstone-ondemand",
    display_name: "Cornerstone OnDemand",
    type: "api",
    domain: "government",
    adapter: "cornerstone_ondemand_api",
    default_toolset: "admin-analytics-tools",
    skill: "cornerstone-ondemand.md",
    summary: "",
    env: ["CSOD_BASE_URL", "CSOD_CLIENT_ID", "CSOD_CLIENT_SECRET", "CSOD_CORP_NAME"],
    connection: { base_url_env: "CSOD_BASE_URL" },
    sync_defaults: { courses: "24h" },
  },
  {
    key: "federal-register",
    display_name: "Federal Register",
    type: "api",
    domain: "government",
    adapter: "federal_register_api",
    default_toolset: "admin-analytics-tools",
    skill: "federal-register.md",
    summary: "",
    env: ["FEDERAL_REGISTER_API_BASE_URL"],
    connection: { base_url_env: "FEDERAL_REGISTER_API_BASE_URL" },
    sync_defaults: { documents: "24h" },
  },
  {
    key: "granicus-govdelivery",
    display_name: "Granicus GovDelivery",
    type: "api",
    domain: "government",
    adapter: "granicus_govdelivery_api",
    default_toolset: "admin-analytics-tools",
    skill: "granicus-govdelivery.md",
    summary: "",
    env: ["GRANICUS_API_BASE_URL", "GRANICUS_API_TOKEN"],
    connection: { base_url_env: "GRANICUS_API_BASE_URL" },
    sync_defaults: { bulletins: "24h" },
  },
  {
    key: "microsoft-entra-id",
    display_name: "Microsoft Entra ID",
    type: "api",
    domain: "government",
    adapter: "microsoft_entra_id_api",
    default_toolset: "admin-analytics-tools",
    skill: "microsoft-entra-id.md",
    summary: "",
    env: ["ENTRA_TENANT_ID", "ENTRA_CLIENT_ID", "ENTRA_CLIENT_SECRET", "ENTRA_GRAPH_ENDPOINT"],
    connection: { base_url_env: "ENTRA_GRAPH_ENDPOINT" },
    sync_defaults: { users: "24h" },
  },
  {
    key: "salesforce-government-cloud",
    display_name: "Salesforce Government Cloud",
    type: "api",
    domain: "government",
    adapter: "salesforce_government_cloud_api",
    default_toolset: "admin-analytics-tools",
    skill: "salesforce-government-cloud.md",
    summary: "",
    env: [
      "SALESFORCE_GOV_INSTANCE_URL",
      "SALESFORCE_GOV_CLIENT_ID",
      "SALESFORCE_GOV_CLIENT_SECRET",
      "SALESFORCE_GOV_USERNAME",
      "SALESFORCE_GOV_PASSWORD",
    ],
    connection: { base_url_env: "SALESFORCE_GOV_INSTANCE_URL" },
    sync_defaults: { cases: "6h" },
  },
  {
    key: "sam-gov",
    display_name: "SAM.gov",
    type: "api",
    domain: "government",
    adapter: "sam_gov_api",
    default_toolset: "admin-analytics-tools",
    skill: "sam-gov.md",
    summary: "",
    env: ["SAM_GOV_API_KEY"],
    connection: { base_url: "https://api.sam.gov" },
    sync_defaults: { entities: "24h" },
  },
  {
    key: "usaspending",
    display_name: "USAspending.gov",
    type: "api",
    domain: "government",
    adapter: "usaspending_api",
    default_toolset: "admin-analytics-tools",
    skill: "usaspending.md",
    summary: "",
    env: ["USASPENDING_API_BASE_URL"],
    connection: { base_url_env: "USASPENDING_API_BASE_URL" },
    sync_defaults: { awards: "24h" },
  },
  {
    key: "workday-government",
    display_name: "Workday Government",
    type: "api",
    domain: "government",
    adapter: "workday_government_api",
    default_toolset: "admin-analytics-tools",
    skill: "workday-government.md",
    summary: "",
    env: [
      "WORKDAY_BASE_URL",
      "WORKDAY_CLIENT_ID",
      "WORKDAY_CLIENT_SECRET",
      "WORKDAY_REFRESH_TOKEN",
      "WORKDAY_RAAS_ENDPOINT",
    ],
    connection: { base_url_env: "WORKDAY_BASE_URL" },
    sync_defaults: { workers: "24h" },
  },
  {
    key: "clio",
    display_name: "Clio",
    type: "api",
    domain: "legal",
    adapter: "clio_api",
    default_toolset: "admin-analytics-tools",
    skill: "clio.md",
    summary: "",
    env: ["CLIO_CLIENT_ID", "CLIO_CLIENT_SECRET", "CLIO_REFRESH_TOKEN", "CLIO_BASE_URL"],
    connection: { base_url_env: "CLIO_BASE_URL" },
    sync_defaults: { matters: "6h" },
  },
  {
    key: "docket-alarm",
    display_name: "Docket Alarm",
    type: "api",
    domain: "legal",
    adapter: "docket_alarm_api",
    default_toolset: "admin-analytics-tools",
    skill: "docket-alarm.md",
    summary: "",
    env: ["DOCKET_ALARM_USERNAME", "DOCKET_ALARM_PASSWORD", "DOCKET_ALARM_BASE_URL"],
    connection: { base_url_env: "DOCKET_ALARM_BASE_URL" },
    sync_defaults: { dockets: "6h" },
  },
  {
    key: "docusign",
    display_name: "DocuSign",
    type: "api",
    domain: "legal",
    adapter: "docusign_api",
    default_toolset: "admin-analytics-tools",
    skill: "docusign.md",
    summary: "",
    env: [
      "DOCUSIGN_ACCOUNT_ID",
      "DOCUSIGN_INTEGRATION_KEY",
      "DOCUSIGN_USER_ID",
      "DOCUSIGN_PRIVATE_KEY",
      "DOCUSIGN_BASE_URL",
    ],
    connection: { base_url_env: "DOCUSIGN_BASE_URL" },
    sync_defaults: { envelopes: "6h" },
  },
  {
    key: "imanage",
    display_name: "iManage Work",
    type: "api",
    domain: "legal",
    adapter: "imanage_api",
    default_toolset: "admin-analytics-tools",
    skill: "imanage.md",
    summary: "",
    env: ["IMANAGE_CLIENT_ID", "IMANAGE_CLIENT_SECRET", "IMANAGE_BASE_URL", "IMANAGE_CUSTOMER_ID"],
    connection: { base_url_env: "IMANAGE_BASE_URL" },
    sync_defaults: { documents: "24h" },
  },
  {
    key: "intapp-conflicts",
    display_name: "Intapp Conflicts",
    type: "api",
    domain: "legal",
    adapter: "intapp_conflicts_api",
    default_toolset: "admin-analytics-tools",
    skill: "intapp-conflicts.md",
    summary: "",
    env: ["INTAPP_CLIENT_ID", "INTAPP_CLIENT_SECRET", "INTAPP_BASE_URL", "INTAPP_TENANT_ID"],
    connection: { base_url_env: "INTAPP_BASE_URL" },
    sync_defaults: { checks: "6h" },
  },
  {
    key: "ironclad",
    display_name: "Ironclad CLM",
    type: "api",
    domain: "legal",
    adapter: "ironclad_api",
    default_toolset: "admin-analytics-tools",
    skill: "ironclad.md",
    summary: "",
    env: ["IRONCLAD_API_KEY", "IRONCLAD_BASE_URL"],
    connection: { base_url_env: "IRONCLAD_BASE_URL" },
    sync_defaults: { contracts: "6h" },
  },
  {
    key: "netdocuments",
    display_name: "NetDocuments",
    type: "api",
    domain: "legal",
    adapter: "netdocuments_api",
    default_toolset: "admin-analytics-tools",
    skill: "netdocuments.md",
    summary: "",
    env: [
      "NETDOCUMENTS_CLIENT_ID",
      "NETDOCUMENTS_CLIENT_SECRET",
      "NETDOCUMENTS_REFRESH_TOKEN",
      "NETDOCUMENTS_BASE_URL",
    ],
    connection: { base_url_env: "NETDOCUMENTS_BASE_URL" },
    sync_defaults: { documents: "24h" },
  },
  {
    key: "pacer",
    display_name: "PACER",
    type: "api",
    domain: "legal",
    adapter: "pacer_api",
    default_toolset: "admin-analytics-tools",
    skill: "pacer.md",
    summary: "",
    env: ["PACER_USERNAME", "PACER_PASSWORD", "PACER_CLIENT_CODE", "PACER_BASE_URL"],
    connection: { base_url_env: "PACER_BASE_URL" },
    sync_defaults: { dockets: "6h" },
  },
  {
    key: "relativity",
    display_name: "Relativity",
    type: "api",
    domain: "legal",
    adapter: "relativity_api",
    default_toolset: "admin-analytics-tools",
    skill: "relativity.md",
    summary: "",
    env: [
      "RELATIVITY_BASE_URL",
      "RELATIVITY_USERNAME",
      "RELATIVITY_PASSWORD",
      "RELATIVITY_WORKSPACE_ID",
    ],
    connection: { base_url_env: "RELATIVITY_BASE_URL" },
    sync_defaults: { documents: "24h" },
  },
  {
    key: "westlaw",
    display_name: "Westlaw Edge",
    type: "api",
    domain: "legal",
    adapter: "westlaw_api",
    default_toolset: "admin-analytics-tools",
    skill: "westlaw.md",
    summary: "",
    env: ["WESTLAW_CLIENT_ID", "WESTLAW_CLIENT_SECRET", "WESTLAW_BASE_URL"],
    connection: { base_url_env: "WESTLAW_BASE_URL" },
    sync_defaults: { searches: "24h" },
  },
  {
    key: "blackrock-aladdin",
    display_name: "BlackRock Aladdin",
    type: "api",
    domain: "financial-services",
    adapter: "blackrock_aladdin_api",
    default_toolset: "admin-analytics-tools",
    skill: "blackrock-aladdin.md",
    summary: "",
    env: ["ALADDIN_API_KEY", "ALADDIN_BASE_URL", "ALADDIN_CLIENT_ID"],
    connection: { base_url_env: "ALADDIN_BASE_URL" },
    sync_defaults: { positions: "6h" },
  },
  {
    key: "bloomberg-terminal",
    display_name: "Bloomberg Terminal",
    type: "api",
    domain: "financial-services",
    adapter: "bloomberg_terminal_api",
    default_toolset: "admin-analytics-tools",
    skill: "bloomberg-terminal.md",
    summary: "",
    env: ["BLOOMBERG_API_HOST", "BLOOMBERG_API_PORT", "BLOOMBERG_DATA_LICENSE_KEY"],
    connection: { base_url_env: "BLOOMBERG_API_HOST" },
    sync_defaults: { securities: "1h" },
  },
  {
    key: "factset",
    display_name: "FactSet",
    type: "api",
    domain: "financial-services",
    adapter: "factset_api",
    default_toolset: "admin-analytics-tools",
    skill: "factset.md",
    summary: "",
    env: ["FACTSET_API_KEY", "FACTSET_API_SECRET", "FACTSET_BASE_URL"],
    connection: { base_url_env: "FACTSET_BASE_URL" },
    sync_defaults: { fundamentals: "24h" },
  },
  {
    key: "lexisnexis-worldcompliance",
    display_name: "LexisNexis WorldCompliance",
    type: "api",
    domain: "financial-services",
    adapter: "lexisnexis_worldcompliance_api",
    default_toolset: "admin-analytics-tools",
    skill: "lexisnexis-worldcompliance.md",
    summary: "",
    env: ["LEXISNEXIS_WC_API_KEY", "LEXISNEXIS_WC_API_SECRET", "LEXISNEXIS_WC_BASE_URL"],
    connection: { base_url_env: "LEXISNEXIS_WC_BASE_URL" },
    sync_defaults: { screenings: "24h" },
  },
  {
    key: "morningstar-direct",
    display_name: "Morningstar Direct",
    type: "api",
    domain: "financial-services",
    adapter: "morningstar_direct_api",
    default_toolset: "admin-analytics-tools",
    skill: "morningstar-direct.md",
    summary: "",
    env: ["MORNINGSTAR_CLIENT_ID", "MORNINGSTAR_CLIENT_SECRET", "MORNINGSTAR_BASE_URL"],
    connection: { base_url_env: "MORNINGSTAR_BASE_URL" },
    sync_defaults: { funds: "24h" },
  },
  {
    key: "nice-actimize",
    display_name: "NICE Actimize",
    type: "api",
    domain: "financial-services",
    adapter: "nice_actimize_api",
    default_toolset: "admin-analytics-tools",
    skill: "nice-actimize.md",
    summary: "",
    env: ["ACTIMIZE_BASE_URL", "ACTIMIZE_API_KEY", "ACTIMIZE_CLIENT_ID", "ACTIMIZE_CLIENT_SECRET"],
    connection: { base_url_env: "ACTIMIZE_BASE_URL" },
    sync_defaults: { alerts: "1h" },
  },
  {
    key: "salesforce-financial-services-cloud",
    display_name: "Salesforce Financial Services Cloud",
    type: "api",
    domain: "financial-services",
    adapter: "salesforce_financial_services_cloud_api",
    default_toolset: "admin-analytics-tools",
    skill: "salesforce-financial-services-cloud.md",
    summary: "",
    env: [
      "SFDC_FSC_CLIENT_ID",
      "SFDC_FSC_CLIENT_SECRET",
      "SFDC_FSC_USERNAME",
      "SFDC_FSC_PASSWORD",
      "SFDC_FSC_BASE_URL",
    ],
    connection: { base_url_env: "SFDC_FSC_BASE_URL" },
    sync_defaults: { households: "6h" },
  },
  {
    key: "splunk",
    display_name: "Splunk",
    type: "api",
    domain: "financial-services",
    adapter: "splunk_api",
    default_toolset: "admin-analytics-tools",
    skill: "splunk.md",
    summary: "",
    env: ["SPLUNK_BASE_URL", "SPLUNK_API_TOKEN", "SPLUNK_APP"],
    connection: { base_url_env: "SPLUNK_BASE_URL" },
    sync_defaults: { events: "1h" },
  },
  {
    key: "workiva",
    display_name: "Workiva",
    type: "api",
    domain: "financial-services",
    adapter: "workiva_api",
    default_toolset: "admin-analytics-tools",
    skill: "workiva.md",
    summary: "",
    env: ["WORKIVA_CLIENT_ID", "WORKIVA_CLIENT_SECRET", "WORKIVA_BASE_URL"],
    connection: { base_url_env: "WORKIVA_BASE_URL" },
    sync_defaults: { filings: "24h" },
  },
  {
    key: "availity",
    display_name: "Availity",
    type: "api",
    domain: "medical-healthcare",
    adapter: "availity_api",
    default_toolset: "admin-analytics-tools",
    skill: "availity.md",
    summary: "",
    env: ["AVAILITY_CLIENT_ID", "AVAILITY_CLIENT_SECRET", "AVAILITY_BASE_URL", "AVAILITY_ORG_ID"],
    connection: { base_url_env: "AVAILITY_BASE_URL" },
    sync_defaults: { claims: "6h" },
  },
  {
    key: "cerner-fhir",
    display_name: "Oracle Cerner (FHIR)",
    type: "api",
    domain: "medical-healthcare",
    adapter: "cerner_fhir_api",
    default_toolset: "admin-analytics-tools",
    skill: "cerner-fhir.md",
    summary: "",
    env: ["CERNER_CLIENT_ID", "CERNER_FHIR_BASE_URL", "CERNER_CLIENT_SECRET", "CERNER_TENANT_ID"],
    connection: { base_url_env: "CERNER_FHIR_BASE_URL" },
    sync_defaults: { patients: "6h" },
  },
  {
    key: "epic-fhir",
    display_name: "Epic (FHIR)",
    type: "api",
    domain: "medical-healthcare",
    adapter: "epic_fhir_api",
    default_toolset: "admin-analytics-tools",
    skill: "epic-fhir.md",
    summary: "",
    env: ["EPIC_CLIENT_ID", "EPIC_FHIR_BASE_URL", "EPIC_PRIVATE_KEY_PATH", "EPIC_SCOPE"],
    connection: { base_url_env: "EPIC_FHIR_BASE_URL" },
    sync_defaults: { patients: "6h" },
  },
  {
    key: "healthstream",
    display_name: "HealthStream",
    type: "api",
    domain: "medical-healthcare",
    adapter: "healthstream_api",
    default_toolset: "admin-analytics-tools",
    skill: "healthstream.md",
    summary: "",
    env: ["HEALTHSTREAM_API_KEY", "HEALTHSTREAM_BASE_URL", "HEALTHSTREAM_FACILITY_ID"],
    connection: { base_url_env: "HEALTHSTREAM_BASE_URL" },
    sync_defaults: { courses: "24h" },
  },
  {
    key: "innovaccer",
    display_name: "Innovaccer",
    type: "api",
    domain: "medical-healthcare",
    adapter: "innovaccer_api",
    default_toolset: "admin-analytics-tools",
    skill: "innovaccer.md",
    summary: "",
    env: [
      "INNOVACCER_API_KEY",
      "INNOVACCER_BASE_URL",
      "INNOVACCER_TENANT_ID",
      "INNOVACCER_CLIENT_SECRET",
    ],
    connection: { base_url_env: "INNOVACCER_BASE_URL" },
    sync_defaults: { cohorts: "6h" },
  },
  {
    key: "micromedex",
    display_name: "IBM Micromedex",
    type: "api",
    domain: "medical-healthcare",
    adapter: "micromedex_api",
    default_toolset: "admin-analytics-tools",
    skill: "micromedex.md",
    summary: "",
    env: ["MICROMEDEX_API_KEY", "MICROMEDEX_BASE_URL", "MICROMEDEX_FACILITY_ID"],
    connection: { base_url_env: "MICROMEDEX_BASE_URL" },
    sync_defaults: { monographs: "24h" },
  },
  {
    key: "nuance-dax",
    display_name: "Nuance DAX",
    type: "api",
    domain: "medical-healthcare",
    adapter: "nuance_dax_api",
    default_toolset: "admin-analytics-tools",
    skill: "nuance-dax.md",
    summary: "",
    env: ["NUANCE_DAX_API_KEY", "NUANCE_DAX_BASE_URL", "NUANCE_DAX_FACILITY_ID"],
    connection: { base_url_env: "NUANCE_DAX_BASE_URL" },
    sync_defaults: { encounters: "6h" },
  },
  {
    key: "pubmed",
    display_name: "PubMed",
    type: "api",
    domain: "medical-healthcare",
    adapter: "pubmed_api",
    default_toolset: "admin-analytics-tools",
    skill: "pubmed.md",
    summary: "",
    env: ["PUBMED_BASE_URL"],
    connection: { base_url_env: "PUBMED_BASE_URL" },
    sync_defaults: { articles: "24h" },
  },
  {
    key: "uptodate",
    display_name: "UpToDate",
    type: "api",
    domain: "medical-healthcare",
    adapter: "uptodate_api",
    default_toolset: "admin-analytics-tools",
    skill: "uptodate.md",
    summary: "",
    env: ["UPTODATE_API_KEY", "UPTODATE_BASE_URL"],
    connection: { base_url_env: "UPTODATE_BASE_URL" },
    sync_defaults: { topics: "24h" },
  },
];
