# Generated by Django 5.2.15 on 2026-06-21 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("db_type", models.CharField(max_length=50)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("database", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "All write operations correctly denied"),
                            (
                                "failed",
                                "One or more write operations succeeded (DANGEROUS)",
                            ),
                            ("error", "Could not complete verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tests_run", models.IntegerField(default=0)),
                ("tests_passed", models.IntegerField(default=0)),
                ("tests_failed", models.IntegerField(default=0)),
                ("details", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("db_type", models.CharField(max_length=50)),
                ("total_tables", models.IntegerField(default=0)),
                ("total_columns", models.IntegerField(default=0)),
                ("total_rows", models.BigIntegerField(default=0)),
                ("schema_manifest", models.JSONField(default=dict)),
                ("llm_analysis", models.JSONField(blank=True, null=True)),
                ("used_llm", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discoveries",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
