allowBuilds:
  canvas: set this to true or false
  msw: set this to true or false
minimumReleaseAgeExclude:
  - '@iblai/data-layer@1.9.2-onboarding-v2.2'
  - '@iblai/iblai-js@1.22.4-onboarding-v2.2'
  - '@iblai/mcp@1.7.8-onboarding-v2.2'
  - '@iblai/web-containers@1.12.2-onboarding-v2.2'
  - '@iblai/web-utils@1.11.11-onboarding-v2.2'
